// common/constants/permission.group.ts
import { Permission as P } from 'src/common/enums/permission.enum';

export const PermissionGroups = {
  PRODUCT: [
    P.PRODUCT_VIEW,
    P.PRODUCT_LIST,
    P.PRODUCT_CREATE,
    P.PRODUCT_UPDATE,
    P.PRODUCT_DELETE,
  ],

  CATEGORY: [
    P.CATEGORY_VIEW,
    P.CATEGORY_LIST,
    P.CATEGORY_CREATE,
    P.CATEGORY_UPDATE,
    P.CATEGORY_DELETE,
  ],

  ORDER: [P.ORDER_VIEW, P.ORDER_LIST, P.ORDER_UPDATE_STATUS, P.ORDER_CANCEL],

  FLASHSALE: [
    P.FLASHSALE_VIEW,
    P.FLASHSALE_LIST,
    P.FLASHSALE_CREATE,
    P.FLASHSALE_UPDATE,
    P.FLASHSALE_DELETE,
  ],

  SHOP: [P.SHOP_VIEW, P.SHOP_LIST, P.SHOP_CREATE, P.SHOP_UPDATE, P.SHOP_DELETE],

  USER: [P.USER_VIEW, P.USER_LIST, P.USER_UPDATE, P.USER_DELETE],

  RBAC: [
    P.ROLE_VIEW,
    P.ROLE_LIST,
    P.ROLE_CREATE,
    P.ROLE_UPDATE,
    P.ROLE_DELETE,
    P.ROLE_ASSIGN,

    P.PERMISSION_VIEW,
    P.PERMISSION_LIST,
    P.PERMISSION_CREATE,
    P.PERMISSION_DELETE,
  ],
};
