export const PATH = {
  HOME: "/",
  USER: "",
  ADMIN: "admin",
  SHOP: "shop",
  MANAGE_USER: "manage-users",
  MANAGE_PRODUCT: "manage-products",
  MANAGE_CATEGORY: "manage-categories",
  MANAGE_ROLE: "manage-roles",
  MANAGE_ORDER: "manage-orders",
  MANAGE_FINANCE: "manage-finances",
  AUTH: "auth",
  SIGNIN: "signin",
  SIGNUP: "signup",
  VERIFY_ACCOUNT: "verify-account",
  FORGOT_PASSWORD: "forgot-password",
  ERROR: "error",
  UNAUTHORIZED: "unathorized",
  NOT_FOUND: "not-found",
  FORBIDDEN: "forbidden",
  BAD_REQUEST: "bad-request",
  INTERNAL_ERROR: "internal-error",
};
